name: Plumber

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  plumber:
    name: Plumber CI/CD Compliance
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run Plumber
        uses: getplumber/plumber@a0658c7fbd82163d75803cce492d18e50ef71afd # v1
        with:
          config: .plumber.yaml
          gate: 90
